server {
    listen 9995 default_server;
    listen [::]:9995 default_server;
    server_name _;
    client_max_body_size 100M;

    location /x1-admin-api {
        proxy_pass http://x1-admin-api:9092/x1-admin-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://x1-admin-api:9092/x1-admin-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api {
        proxy_pass http://x1-admin-api:9092/x1-admin-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html/x1pad/dist;
        index index.html;
        add_header Cache-Control "no-cache, private";
        expires -1s;
        try_files $uri $uri/ /index.html;
    }
}
