 server {
        listen       9999 default_server;
        listen       [::]:9999 default_server;
        server_name  _;
        
        client_max_body_size 100M;
        
          
         location /api/ {
           proxy_pass  http://x1-admin-api:9092/x1-admin-api/;
           proxy_set_header Host $host:9092;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
           proxy_set_header REMOTE-HOST        $remote_addr;
           proxy_set_header X-Forwarded-Proto  $scheme;
         }
         location /api/websocket {
           # 核心：路径重写（保留所有查询参数）
           rewrite ^/api/(websocket.*)$ /x1-admin-api/$1 break;

           # 后端 WebSocket 服务地址
           proxy_pass http://192.168.80.82:9092;    #修改为正确的ip

           # WebSocket 必须的协议升级配置
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";

           # 解决 60 秒无数据自动断开问题（设置为1天）
           proxy_read_timeout 86400;
           proxy_send_timeout 86400;

           # 可选：传递真实客户端信息给后端
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         }
         location /api {
           proxy_pass  http://x1-admin-api:9092/x1-admin-api/;
           proxy_set_header Host $host:9092;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
           proxy_set_header REMOTE-HOST        $remote_addr;
           proxy_set_header X-Forwarded-Proto  $scheme;
         }
        
         location /x1-admin-api {
           proxy_pass  http://x1-admin-api:9092/x1-admin-api/;
           proxy_set_header Host $host:9092;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
           proxy_set_header REMOTE-HOST        $remote_addr;
           proxy_set_header X-Forwarded-Proto  $scheme;
         }
         
        location / {
          root  /usr/share/nginx/html/x1pc/dist;
          index  index.html index.htm;
          add_header Cache-Control no-cache;
          add_header Cache-Control private;
          expires -1s;
          try_files $uri $uri/ /index.html;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
